name: test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  test-sagemaker_scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9  # You can specify your Python version here.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd sagemaker_scripts && pipenv install --deploy --dev && pipenv run pytest ../tests/sagemaker_scripts/

  test-streamlit_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9  # You can specify your Python version here.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd streamlit_app && pipenv install --deploy --dev && pipenv run pytest ../tests/streamlit_app/
